### ISSUE TITLE
Free version in ePub format

### ISSUE THREAD

**Issue by doliG** [valentinogagliardi/Little-JavaScript-Book#3]
Hello,

First thanks a lot for this great book :)
If I might suggest, it could be great to have epub version of the free book.

Thanks :)

**Comment by valentinogagliardi** [comment]
Thanks for you words. Let's see if there's more people interested on the ePub.

**Comment by doliG** [comment]
Took me literally 5min to compile an epub with pandocs.

Here is the command, if it can helps:
```bash
pandoc --toc intro.md chapter1.md chapter3.md chapter4.md chapter5.md chapter6.md chapter7.md chapter8.md -o Little_JavaScript_Book.epub
```
